### ISSUE TITLE
How json minify?

### ISSUE THREAD

**Issue by Yuriy-Svetlov** [nirvana-msu/yii2-jsonld-helper#4]
How make json minify?

**Comment by nirvana-msu** [comment]
You've already got a [reply](https://github.com/lanthaler/JsonLD/issues/74#issuecomment-278491352) from the owner of the underlying [lanthaler/JsonLD](https://github.com/lanthaler/JsonLD) library.

This extension merely provides a handy shortcuts for the most common use-cases. E.g. all that `JsonLDHelper::add` method does is, in essense:

```php
$compacted = JsonLD::compact((object)$doc, $context);
$view = Yii::$app->getView();
$view->params['jsonld'][] = json_encode($compacted, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
```

So you can create the script however you like (minified etc), then just add it to the `'jsonld'` view parameter like above, so it could be registered when you call `JsonLDHelper::registerScripts` in the layout.
